# Generated by Django 3.2.15 on 2023-07-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_useractivity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='departamento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
