# Generated by Django 3.2.15 on 2024-03-07 15:41

import control_creacion_usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen_sig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to=control_creacion_usuario.models.content_file_name_adjunto)),
            ],
            options={
                'verbose_name': 'Imagen_sig',
                'verbose_name_plural': 'Imagenes_sig',
            },
        ),
    ]
