# Generated by Django 3.2.15 on 2024-05-06 20:56

import control_creacion_usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_creacion_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF_sig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to=control_creacion_usuario.models.content_file_name_adjunto_pdf)),
            ],
            options={
                'verbose_name': 'pdf_sig',
                'verbose_name_plural': 'pdfs_sig',
            },
        ),
        migrations.AlterField(
            model_name='imagen_sig',
            name='archivo_adjunto',
            field=models.ImageField(blank=True, null=True, upload_to=control_creacion_usuario.models.content_file_name_adjunto),
        ),
    ]
