# Generated by Django 3.2.15 on 2023-07-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_remove_protocolosolicitud_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolosolicitud',
            name='orde_trabajo',
        ),
        migrations.AddField(
            model_name='protocolosolicitud',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='protocolosolicitud',
            name='estado',
            field=models.CharField(blank=True, choices=[('EJECUTADO', 'EJECUTADO'), ('RECHAZADO', 'RECHAZADO'), ('EN PROCESO', 'EN PROCESO'), ('RECIBIDO', 'RECIBIDO')], default='RECIBIDO', max_length=100),
        ),
    ]
