# Generated by Django 3.2.15 on 2023-07-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_auto_20230707_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolosolicitud',
            name='estado',
            field=models.CharField(blank=True, choices=[('RECHAZADO', 'RECHAZADO'), ('EN PROCESO', 'EN PROCESO'), ('EJECUTADO', 'EJECUTADO'), ('RECIBIDO', 'RECIBIDO')], default='RECIBIDO', max_length=100),
        ),
    ]
