# Generated by Django 3.2.15 on 2023-07-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_alter_protocolosolicitud_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolosolicitud',
            name='estado',
            field=models.CharField(blank=True, choices=[('EN PROCESO', 'EN PROCESO'), ('RECIBIDO', 'RECIBIDO'), ('RECHAZADO', 'RECHAZADO'), ('EJECUTADO', 'EJECUTADO')], default='RECIBIDO', max_length=100),
        ),
    ]
