# Generated by Django 3.2.15 on 2023-07-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0011_alter_protocolosolicitud_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolosolicitud',
            name='estado',
            field=models.CharField(blank=True, choices=[('RECHAZADO', 'RECHAZADO'), ('EJECUTADO', 'EJECUTADO'), ('EN PROCESO', 'EN PROCESO'), ('RECIBIDO', 'RECIBIDO')], default='RECIBIDO', max_length=100),
        ),
    ]
