# Generated by Django 3.2.15 on 2023-10-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0024_alter_protocolosolicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolosolicitud',
            name='corre_solicitante',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='protocolosolicitud',
            name='estado',
            field=models.CharField(blank=True, choices=[('EN PROCESO', 'EN PROCESO'), ('RECIBIDO', 'RECIBIDO'), ('RECHAZADO', 'RECHAZADO'), ('EJECUTADO', 'EJECUTADO')], default='RECIBIDO', max_length=100),
        ),
    ]
