# Generated by Django 3.2.15 on 2023-10-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0025_auto_20231004_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolosolicitud',
            name='estado',
            field=models.CharField(blank=True, choices=[('RECIBIDO', 'RECIBIDO'), ('EJECUTADO', 'EJECUTADO'), ('RECHAZADO', 'RECHAZADO'), ('EN PROCESO', 'EN PROCESO')], default='RECIBIDO', max_length=100),
        ),
    ]
