# Generated by Django 3.2.15 on 2023-10-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0028_alter_protocolosolicitud_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolosolicitud',
            name='estado',
            field=models.CharField(blank=True, choices=[('RECHAZADO', 'RECHAZADO'), ('RECIBIDO', 'RECIBIDO'), ('EJECUTADO', 'EJECUTADO'), ('EN PROCESO', 'EN PROCESO')], default='RECIBIDO', max_length=100),
        ),
    ]
