# Generated by Django 3.2.15 on 2023-10-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0031_alter_protocolosolicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolosolicitud',
            name='direccion',
            field=models.CharField(blank=True, choices=[('Dirección de Vivienda, Barrio y Territorio', 'Dirección de Vivienda, Barrio y Territorio'), ('Dirección desarrollo Económico y Cooperación Internacional', 'Dirección desarrollo Económico y Cooperación Internacional'), ('', ''), ('Dirección de Operaciones', 'Dirección de Operaciones'), ('Dirección de Administración y Finaza', 'Dirección de Administración y Finaza'), ('Dirección de Desarrollo Cultural', 'Dirección de Desarrollo Cultural'), ('Dirección de Medioambiente', 'Dirección de Medioambiente'), ('Dirección de Género, Mujeres y Diversidades', 'Dirección de Género, Mujeres y Diversidades'), ('Dirección de Obras Municipales', 'Dirección de Obras Municipales'), ('Dirección de Desarrollo Comunitario', 'Dirección de Desarrollo Comunitario'), ('Dirección de Tránsito y Transporte públicos', 'Dirección de Tránsito y Transporte públicos'), ('Dirección de Seguridad Ciudadana', 'Dirección de Seguridad Ciudadana')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='protocolosolicitud',
            name='estado',
            field=models.CharField(blank=True, choices=[('RECIBIDO', 'RECIBIDO'), ('EN PROCESO', 'EN PROCESO'), ('EJECUTADO', 'EJECUTADO'), ('RECHAZADO', 'RECHAZADO')], default='RECIBIDO', max_length=100),
        ),
    ]
