# Generated by Django 3.2.15 on 2023-10-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0032_auto_20231023_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolosolicitud',
            name='direccion',
            field=models.CharField(blank=True, choices=[('Dirección desarrollo Económico y Cooperación Internacional', 'Dirección desarrollo Económico y Cooperación Internacional'), ('Dirección de Desarrollo Comunitario', 'Dirección de Desarrollo Comunitario'), ('Dirección de Desarrollo Cultural', 'Dirección de Desarrollo Cultural'), ('', ''), ('Dirección de Operaciones', 'Dirección de Operaciones'), ('Dirección de Tránsito y Transporte públicos', 'Dirección de Tránsito y Transporte públicos'), ('Dirección de Administración y Finaza', 'Dirección de Administración y Finaza'), ('Dirección de Vivienda, Barrio y Territorio', 'Dirección de Vivienda, Barrio y Territorio'), ('Dirección de Obras Municipales', 'Dirección de Obras Municipales'), ('Dirección de Medioambiente', 'Dirección de Medioambiente'), ('Dirección de Seguridad Ciudadana', 'Dirección de Seguridad Ciudadana'), ('Dirección de Género, Mujeres y Diversidades', 'Dirección de Género, Mujeres y Diversidades')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='protocolosolicitud',
            name='estado',
            field=models.CharField(blank=True, choices=[('RECHAZADO', 'RECHAZADO'), ('RECIBIDO', 'RECIBIDO'), ('EJECUTADO', 'EJECUTADO'), ('EN PROCESO', 'EN PROCESO')], default='RECIBIDO', max_length=100),
        ),
    ]
