# Generated by Django 3.2.15 on 2023-11-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0042_auto_20231117_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolosolicitud',
            name='direccion',
            field=models.CharField(blank=True, choices=[('Dirección de Obras Municipales', 'Dirección de Obras Municipales'), ('Dirección de Operaciones', 'Dirección de Operaciones'), ('', ''), ('SECPLA', 'SECPLA'), ('Dirección de Seguridad Ciudadana', 'Dirección de Seguridad Ciudadana'), ('Dirección de Desarrollo Cultural', 'Dirección de Desarrollo Cultural'), ('Dirección de Desarrollo Comunitario', 'Dirección de Desarrollo Comunitario'), ('Dirección desarrollo Económico y Cooperación Internacional', 'Dirección desarrollo Económico y Cooperación Internacional'), ('Dirección de Administración y Finaza', 'Dirección de Administración y Finaza'), ('Dirección de Medioambiente', 'Dirección de Medioambiente'), ('Dirección de Vivienda, Barrio y Territorio', 'Dirección de Vivienda, Barrio y Territorio'), ('Dirección de Género, Mujeres y Diversidades', 'Dirección de Género, Mujeres y Diversidades'), ('Dirección de Tránsito y Transporte públicos', 'Dirección de Tránsito y Transporte públicos')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='protocolosolicitud',
            name='estado',
            field=models.CharField(blank=True, choices=[('RECHAZADO', 'RECHAZADO'), ('EN PROCESO', 'EN PROCESO'), ('RECIBIDO', 'RECIBIDO'), ('EJECUTADO', 'EJECUTADO')], default='RECIBIDO', max_length=100),
        ),
    ]
