# Generated by Django 3.2.15 on 2023-11-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0045_auto_20231122_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolosolicitud',
            name='direccion',
            field=models.CharField(blank=True, choices=[('Dirección desarrollo Económico y Cooperación Internacional', 'Dirección desarrollo Económico y Cooperación Internacional'), ('Dirección de Administración y Finaza', 'Dirección de Administración y Finaza'), ('Dirección de Desarrollo Comunitario', 'Dirección de Desarrollo Comunitario'), ('Dirección de Vivienda, Barrio y Territorio', 'Dirección de Vivienda, Barrio y Territorio'), ('Dirección de Obras Municipales', 'Dirección de Obras Municipales'), ('', ''), ('Dirección de Operaciones', 'Dirección de Operaciones'), ('Dirección de Desarrollo Cultural', 'Dirección de Desarrollo Cultural'), ('SECPLA', 'SECPLA'), ('Dirección de Género, Mujeres y Diversidades', 'Dirección de Género, Mujeres y Diversidades'), ('Dirección de Seguridad Ciudadana', 'Dirección de Seguridad Ciudadana'), ('Dirección de Tránsito y Transporte públicos', 'Dirección de Tránsito y Transporte públicos'), ('Dirección de Medioambiente', 'Dirección de Medioambiente')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='protocolosolicitud',
            name='estado',
            field=models.CharField(blank=True, choices=[('RECHAZADO', 'RECHAZADO'), ('RECIBIDO', 'RECIBIDO'), ('EN PROCESO', 'EN PROCESO'), ('EJECUTADO', 'EJECUTADO')], default='RECIBIDO', max_length=100),
        ),
    ]
