# Generated by Django 3.2.15 on 2024-01-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0049_auto_20231214_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolosolicitud',
            name='direccion',
            field=models.CharField(blank=True, choices=[('Dirección de Seguridad Ciudadana', 'Dirección de Seguridad Ciudadana'), ('Dirección de Desarrollo Cultural', 'Dirección de Desarrollo Cultural'), ('', ''), ('Dirección de Vivienda, Barrio y Territorio', 'Dirección de Vivienda, Barrio y Territorio'), ('Dirección de Tránsito y Transporte públicos', 'Dirección de Tránsito y Transporte públicos'), ('Dirección de Género, Mujeres y Diversidades', 'Dirección de Género, Mujeres y Diversidades'), ('SECPLA', 'SECPLA'), ('Dirección de Medioambiente', 'Dirección de Medioambiente'), ('Dirección desarrollo Económico y Cooperación Internacional', 'Dirección desarrollo Económico y Cooperación Internacional'), ('Dirección de Administración y Finaza', 'Dirección de Administración y Finaza'), ('Dirección de Obras Municipales', 'Dirección de Obras Municipales'), ('Dirección de Operaciones', 'Dirección de Operaciones'), ('Dirección de Desarrollo Comunitario', 'Dirección de Desarrollo Comunitario')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='protocolosolicitud',
            name='estado',
            field=models.CharField(blank=True, choices=[('EJECUTADO', 'EJECUTADO'), ('EN PROCESO', 'EN PROCESO'), ('RECHAZADO', 'RECHAZADO'), ('RECIBIDO', 'RECIBIDO')], default='RECIBIDO', max_length=100),
        ),
    ]
